"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";
import Navbar from "./navbar/navbar";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname()
  console.log("current route ", pathname)
  return (
    <html lang="en">
      <body>
        {pathname !== "/login" && pathname !== "/register" && (
            <header>
            <Navbar />
          </header>

        )}
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
